### ISSUE TITLE
The response did not match the response schema.

### ISSUE THREAD

**Issue by emn-dev** [maxio-com/ab-typescript-sdk#87]
Hello!

On a 200 response from "Read Subscription" (https://developers.maxio.com/typescript/advanced-billing-api/api-endpoints/subscriptions/read-subscription) here is part of the JSON returned:

![image](https://github.com/user-attachments/assets/e034e4e4-8bcf-4603-bb35-99c7d8a4ebcc)

When using the sdk we get a schema error from apiMatic:

![image](https://github.com/user-attachments/assets/2a555704-cbce-4ee3-a7f8-8b3bacaceeae)

The entry for "imported" in CancellationMethod does not exist.

https://github.com/maxio-com/ab-typescript-sdk/blob/bed2205ce30330b5d08bc10def1bcc58aa6009e0/src/models/cancellationMethod.ts#L12-L18

Can you add that entry?

**Comment by maciej-nedza** [comment]
Thanks for reporting @emn-dev , now it's fixed in 5.1.0 https://github.com/maxio-com/ab-typescript-sdk/releases/tag/5.1.0
https://www.npmjs.com/package/@maxio-com/advanced-billing-sdk/v/5.1.0
