### ISSUE TITLE
fetch archived price points

### ISSUE THREAD

**Issue by f3oall** [maxio-com/ab-typescript-sdk#92]
Hey, it seems like we can fetch only not archived price points with your library now, however it seems like API itself supports `archived=true` query param (please correct me if I'm wrong).

Should we wait for the fix and if so when we should expect it?

**Comment by maciej-nedza** [comment]
Hey @f3oall , you mean `List Product Price Points` -  https://developers.maxio.com/http/advanced-billing-api/api-endpoints/product-price-points/list-product-price-points, correct?
Then seems like you're right, thanks for reporting. We'll add support for it to the SDK. We're planning SDK for this or next week.

**Comment by f3oall** [comment]
Glad to help. Yeah, I meant this endpoint: https://developers.maxio.com/http/advanced-billing-api/api-endpoints/product-price-points/list-product-price-points
And this one: https://developers.maxio.com/http/advanced-billing-api/api-endpoints/product-price-points/list-all-product-price-points

The second one is very similar to the first, right? So it shouldn't be an issue?

**Comment by maciej-nedza** [comment]
Fixed in `6.0.0`. `archived` is added to `listProductPricePoints`
Unfortunately, the second one doesn’t support this functionality. While these endpoints are similar, they operate slightly differently on the backend.
